### PR TITLE
Edition registration section

### LINKED ISSUE #57: Edition registration page
We still need to create the page that makes a user a participant of an ongoing edition.

### PR DESCRIPTION
**Pull request by pedrosilva17**
Closes #57 
No mocks were provided for this ~~page~~ section, so any ideas are welcome. My idea is to have a photo taken during the previous editions, as a sort of visual showcase of what the student can expect after securing their spot in the event.
Perhaps multiple pictures in a grid? That would also help with smaller screens.

The button has a unique hover animation to make it stand out from the rest of them.

image

### CODE REVIEW

**Comment by pedrosilva17** [comment]
The section is now placed in the home page, so it is no longer a new page.

**Comment by Naapperas** [comment]
Please rebase this

**Comment by pedrosilva17** [comment]
image

**Comment by pedrosilva17** [comment]
image

**Review by toni-santos — APPROVED** [review]
:+1:

**Review by pedronunes19 — APPROVED** [review]

**Pull request merged**
