### PR TITLE
Added sponsor table

### LINKED ISSUE #46: Add sponsor table
Add a relation that associates a company with an edition and stores its tier and any other relevant information.

### PR DESCRIPTION
**Pull request by Naapperas**
Closes #46

### CODE REVIEW

**Comment by Naapperas** [comment]
I do not know if we need something more other than this.

**Comment by ttoino** [comment]
> I do not know if we need something more other than this.

You should add/modify the relevant admin pages. Namely, the user edit/creation page for companies should not have the tier anymore and there should be a page for sponsors.

You should also add a factory and modify the seeder to create sponsors.

**Comment by Naapperas** [comment]
> > I do not know if we need something more other than this.
> 
> You should add/modify the relevant admin pages. Namely, the user edit/creation page for companies should not have the tier anymore and there should be a page for sponsors.
> 
> You should also add a factory and modify the seeder to create sponsors.

Oh, you're right. On it.

**Review by diogofonte — DISMISSED** [review]
LGTM!

**Review by toni-santos — APPROVED** [review]

**Review by diogofonte — APPROVED** [review]

**Pull request merged**
